CREATE TABLE [dbo].[BTRG_PackingOrder]
(
	PackingOrderId VARCHAR(26) NOT NULL CONSTRAINT DF_BTRG_PackingOrder_PackingOrderId DEFAULT (''),
	PackingOrderDate DATETIME NOT NULL CONSTRAINT DF_BTRG_PackingOrder_PackingOrderDate DEFAULT ('3000-01-01'),
	PackingOrderCode VARCHAR(20) NOT NULL CONSTRAINT DF_BTRG_PackingOrder_PackingOrderCode DEFAULT (''),

	CustomerId VARCHAR(26) NOT NULL CONSTRAINT DF_BTRG_PackingOrder_CustomerId DEFAULT (''),
	CustomerCode VARCHAR(10) NOT NULL CONSTRAINT DF_BTRG_PackingOrder_CustomerCode DEFAULT (''),
	CustomerName VARCHAR(100) NOT NULL CONSTRAINT DF_BTRG_PackingOrder_CustomerName DEFAULT (''),
	Alamat VARCHAR(200) NOT NULL CONSTRAINT DF_BTRG_PackingOrder_AlamatKirim DEFAULT (''),
	NoTelp VARCHAR(20) NOT NULL CONSTRAINT DF_BTRG_PackingOrder_NoTelp DEFAULT (''),

	FakturId VARCHAR(26) NOT NULL CONSTRAINT DF_BTRG_PackingOrder_FakturId DEFAULT (''),
	FakturCode VARCHAR(26) NOT NULL CONSTRAINT DF_BTRG_PackingOrder_FakturCode DEFAULT (''),
	FakturDate DATETIME NOT NULL CONSTRAINT DF_BTRG_PackingOrder_FakturDate DEFAULT ('3000-01-01'),
	AdminName VARCHAR(100) NOT NULL CONSTRAINT DF_BTRG_PackingOrder_AdminName DEFAULT (''),

	Latitude DECIMAL(18, 15) NOT NULL CONSTRAINT DF_BTRG_PackingOrder_Latitude DEFAULT (0),
	Longitude DECIMAL(18, 15) NOT NULL CONSTRAINT DF_BTRG_PackingOrder_Longitude DEFAULT (0),
	Accuracy INT NOT NULL CONSTRAINT DF_BTRG_PackingOrder_Accuracy DEFAULT (0),

	CONSTRAINT PK_BTRG_PackingOrder PRIMARY KEY CLUSTERED (PackingOrderId)
)
