CREATE TABLE [dbo].[BTRG_PrintLog]
(
	PrintLogId VARCHAR(26) NOT NULL CONSTRAINT DF_BTRG_PrintLog_PrintLogId DEFAULT(''),
	PrintLogTimestamp DATETIME NOT NULL CONSTRAINT DF_BTRG_PrintLog_PrintLogTimestamp DEFAULT('3000-01-01'),
	DocType VARCHAR(10) NOT NULL CONSTRAINT DF_BTRG_PrintLog_DocType DEFAULT(''),

	CONSTRAINT PK_BTRG_PrintLog PRIMARY KEY CLUSTERED(PrintLogId)
)
